version: "3"
services:
  #php
  falcons_app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: digitalocean.com/php
    container_name: falcons_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: falcons_app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - falcons_app_network

  #nginx
  falcons_nginx:
    image: nginx:alpine
    container_name: falcons_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - falcons_app_network

    #mysql
    # falcons_mysql:
    #   image: mysql:5.7.22
    #   container_name: falcons_mysql
    #   restart: unless-stopped
    #   tty: true
    #   ports:
    #     - "33006:3306"
    #   environment:
    #     MYSQL_DATABASE: falcons
    #     MYSQL_ROOT_PASSWORD: falcons
    #     SERVICE_TAGS: dev
    #     SERVICE_NAME: mysql
    #   volumes:
    #     - dbdata:/var/lib/mysql
    #     - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    #   networks:
    #     - falcons_app_network

  falcons_postgres:
    image: postgres
    container_name: falcons_postgres
    environment:
      POSTGRES_PASSWORD: "falcons"
    ports:
      - "15432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - falcons_app_network

  falcons_pgadmin:
    image: dpage/pgadmin4
    container_name: falcons_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com.br"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - falcons_postgres
    networks:
      - falcons_app_network

#networks
networks:
  falcons_app_network:
    driver: bridge
# #volumes
# volumes:
#   dbdata:
#     driver: local
